[env]
PATH = "/app/node_modules/.bin:$PATH"

[phases.setup]
nixPkgs = ["nodejs_20"]

[phases.install]
cmd = "corepack enable && npx npm install"

[phases.build]
cmd = "corepack enable && npx npm run build"

[start]
cmd = "npm start"